packages/dataiku/azure/ansible/environment/config.yml
updated the version of dataiku to 10.0.4
=> updated the version of dataiku to 10.0.4

packages/dataiku/azure/ansible/roles/dataiku-upgrade/tasks/main.yml
updated the pigz and ip_v4_address
=> updated the pigz and ip_v4_address

packages/dashboard-backend/dashboard-lib/src/main/java/com/daimler/data/db/repo/report/ReportCustomRepositoryImpl.java, packages/dashboard-backend/dashboard-lib/src/main/resources/api/Report.yaml
Fixing issues:
1.  Create lov was failing when user give any special/reserved character.
2.  Added few field as mandatory while creation of report.
=> Handling reserved character case while creating new lovs

packages/frontend/src/components/mbc/createNewSolution/description/Description.scss, packages/frontend/src/components/mbc/createNewSolution/description/Description.tsx, packages/frontend/src/globals/constants.ts
Enabled info modal for "Register support of additional resources" field
Fixed some bugs
=> enabled info modal for newly added field

deployment/kubernetes/helm/charts/backend/templates/backend/deployment.yaml, deployment/kubernetes/helm/charts/backend/templates/backend/ingress.yaml, deployment/kubernetes/helm/charts/backend/templates/backend/service.yaml, deployment/kubernetes/helm/charts/frontend/templates/frontend/deployment.yaml, deployment/kubernetes/helm/charts/frontend/templates/frontend/ingress.yaml, deployment/kubernetes/helm/charts/frontend/templates/frontend/nginx.yaml, deployment/kubernetes/helm/charts/frontend/templates/frontend/service.yaml, deployment/kubernetes/helm/charts/frontend/templates/ingress-controller/traefik-http-redirect.yaml, deployment/kubernetes/helm/charts/frontend/templates/traefik/traefik-http-redirect.yaml, deployment/kubernetes/helm/charts/frontend/values.yaml, deployment/kubernetes/helm/values.yaml
=> Chnages on frontend

deployment/kubernetes/helm/charts/airflow/values.yaml, deployment/kubernetes/helm/charts/bitnami-postgresql/files/docker-entrypoint-initdb.d/02-schema-creation.sql, deployment/kubernetes/helm/charts/bitnami-postgresql/files/docker-entrypoint-initdb.d/03-schema-data.sql, deployment/kubernetes/helm/charts/clamav/values.yaml, deployment/kubernetes/helm/charts/dashboard/values.yaml, deployment/kubernetes/helm/charts/i3postgresql/files/localdb-init/02-schema-creation.sql, deployment/kubernetes/helm/charts/i3postgresql/files/localdb-init/03-schema-data.sql, deployment/kubernetes/helm/charts/naas/values.yaml, deployment/kubernetes/helm/values.yaml
=> updated db scripts

packages/frontend/.build/webpack/prod.js, packages/frontend/package.json, packages/storage-mfe/webpack.prod.config.js
update splitChunk with chunk as 'async'
=> update publicPath for both dna frontend and storage-mfe

packages/frontend/docker-start.sh
=> issue with replacement

deployment/kubernetes/helm/charts/clamav/templates/clamav-deployment.yaml
I kept the intialDelaySeconds for liveness a bit higher value to avoid the restarts .
=> Added probes for clamAV

packages/dataiku/azure/ansible/roles/dataiku-upgrade/tasks/main.yml
Whenever we are executing with --skip-tags = always with roles , it was disabling the gathering facts so for this we need to explicitly load all gathered facts
=> Added new task to load gathered facts.

packages/backend/dnambc-lib/src/main/java/com/daimler/data/controller/DataSourceController.java
Issue: Not able to create datasource using create solution.
Fix: removed cache implementation for data source apis.
=> fix for data source create api

packages/storage-mfe/docker-start.sh
Updated docker-start.sh file with latest changes
=> Storage mfe build error fix

packages/dashboard-backend/dashboard-lib/src/main/resources/api/Report.yaml
Removed required check for "Integrated in Portal", "Agile Release Train" and "Tags", "Customer - Comment", "Kpi - Comment"
=> removing required check for report fields

packages/storage-mfe/src/components/Bucket/Bucket.js, packages/storage-mfe/src/components/Bucket/BucketList.js, packages/storage-mfe/src/components/ConnectionInfo/ConnectionModal.js, packages/storage-mfe/src/components/ConnectionInfo/ConnectionModal.scss, packages/storage-mfe/src/components/Explorer/FileExplorer.js, packages/storage-mfe/src/components/Explorer/FileExplorer.scss, packages/storage-mfe/src/components/Explorer/redux/fileExplorer.actions.js
2. include OK button for the Connection Modal and corresponding css style
3. Hide additional text shown by chonky library in context menu and also show hidden files options
4. update date format for all the files and folders
5. show confirmation modal on deleting a file or folder
6. open confirmation modal on opening existing folder or on navigating back with empty folder
7. add validation for folder name
=> 1. update  title from My Buckets to My Storage

packages/storage-mfe/src/components/Bucket/CreateBucket.js, packages/storage-mfe/src/components/Bucket/CreateBucket.scss, packages/storage-mfe/src/components/Bucket/redux/bucket.actions.js, packages/storage-mfe/src/components/ConnectionInfo/ConnectionModal.js
2. close connection modal on clicking OK button
=> 1. add goBack link on create new bucket page

packages/storage-mfe/src/components/Explorer/FileExplorer.js
2. update the objectName for the folders in draft state
=> 1. reset error message on closing create folder modal

packages/frontend/src/components/mbc/admin/Administration.tsx, packages/storage-mfe/package.json, packages/storage-mfe/src/apis/fileExplorer.api.js, packages/storage-mfe/src/components/Explorer/FileExplorer.js, packages/storage-mfe/src/components/Explorer/Upload.js, packages/storage-mfe/src/components/Explorer/redux/fileExplorer.actions.js, packages/storage-mfe/src/server/utils.js
2. update logic for the folder path
3. in Admin tab ensure tab-content are also rendered based on the permission (to avoid unnecessary api calls of tabs not to be rendered)
=> 1. serialize params to encode special characters

packages/storage-mfe/src/components/Bucket/BucketList.js, packages/storage-mfe/src/components/Explorer/FileExplorer.js, packages/storage-mfe/src/components/Explorer/Utils.js, packages/storage-mfe/src/components/Explorer/redux/fileExplorer.actions.js
1. remove unnecessary validation to filter falsy values
2. handle edge cases for in draft stage
=> handle edge cases for in draft nested folders

packages/frontend/package.json, packages/frontend/src/components/formElements/modal/confirmModal/ConfirmModal.md, packages/frontend/src/components/formElements/modal/confirmModal/ConfirmModal.tsx, packages/frontend/src/components/mbc/addUser/AddUser.md, packages/frontend/src/components/mbc/addUser/AddUser.styleguide.scss, packages/frontend/src/components/mbc/addUser/AddUser.tsx, packages/frontend/styleguide.config.js, packages/storage-mfe/package.json, packages/storage-mfe/src/components/Bucket/Bucket.js, packages/storage-mfe/src/components/Bucket/Bucket.md, packages/storage-mfe/src/styleguide/Wrapper.js, packages/storage-mfe/styleguide.config.js
2. include markdown documentation for few of the  component files
3. add necessary JSDoc
=> 1. add react-styleguidist

deployment/kubernetes/helm/charts/backend/templates/backend/deployment.yaml, deployment/kubernetes/helm/charts/backend/templates/secrets/vault-secret.yaml, deployment/kubernetes/helm/charts/backend/values.yaml
=> updating backend env

packages/frontend/src/components/mbc/addUser/AddUser.tsx, packages/storage-mfe/src/components/Bucket/BucketList.js, packages/storage-mfe/src/components/Bucket/BucketList.scss, packages/storage-mfe/src/components/Bucket/CreateBucket.js, packages/storage-mfe/src/components/Bucket/CreateBucket.scss
1. display first and last name for the collaborators while edit and also display during All buckets page
2. include lastModifiedOn column in All Buckets page
3. add necessary css changes
=> Storage api integration

packages/storage-mfe/src/components/Explorer/FileExplorer.js
=> in File explorer include "Publish to Trino" button on both toolbar and context menu

deployment/kubernetes/helm/charts/clamav/templates/rest/clamav-rest-deployment.yaml, deployment/kubernetes/helm/charts/clamav/values.yaml
adding naas broker env in malware
=> adding naas broker env in malware

packages/frontend/src/components/mbc/notification/Notifications.tsx, packages/frontend/src/components/mbc/userSettings/notificationsSettings/notificationsSettings.tsx, packages/storage-mfe/src/components/Bucket/CreateBucket.js
2. update condition within useEffect for edit Bucket
3. rename Persistence to Storage in notification settings
=> 1. wrap notification messageDetails in markdownParser function

deployment/kubernetes/helm/charts/model-registry/values.yaml
added host and cert manager as env
=> Update values.yaml for model reg

packages/storage-backend/storage-lib/src/main/java/com/daimler/data/service/storage/BaseStorageService.java, packages/storage-backend/storage-lib/src/main/resources/application.yml
Environment variable to use as an exposed minio url for dataiku connection.
=> Added env variable to use as an exposed url for minio

packages/frontend/.build/webpack/base.js, packages/storage-mfe/webpack.prod.config.js
=> have only dynamic variable accessing through window object  and remove the variable accessing env

packages/storage-mfe/src/components/ConnectionInfo/ConnectionModal.js
=> show dataiku connected projects, even if the user doesn't have list of dataiku projects

packages/storage-mfe/src/components/Explorer/CustomFileActions.js, packages/storage-mfe/src/components/Explorer/FileExplorer.js, packages/storage-mfe/src/components/Explorer/Upload.js, packages/storage-mfe/src/components/Explorer/redux/fileExplorer.actions.js
show this button along side Upload File button
=> implement Upload Folder button

packages/frontend/src/components/mbc/pipeline/createNewPipeline/CreateNewPipeline.tsx, packages/storage-mfe/src/components/Bucket/CreateBucket.js
=> restrict owner to be added as a collaborators in storage bucket and pipeline creation

packages/dataiku/azure/ansible/environment/config.yml
updated dataiku version to "11.0.0"
=> updated dataiku version to "11.0.0"

packages/data-product-mfe/src/components/Form/BasicInformation/index.js, packages/data-product-mfe/src/components/Form/BasicInformation/styles.scss, packages/data-product-mfe/src/components/Form/ClassificationAndConfidentiality/index.js, packages/data-product-mfe/src/components/Form/TransNationalDataTransfer/index.js
=> update the radio button checked issue

packages/frontend/src/components/mbc/allSolutions/AllSolutions.tsx
covered this change in my bookmarks and my solution also
=> Solution count display in all solutions and other places wherever make sense

packages/data-product-mfe/src/Utility/formData.js, packages/data-product-mfe/src/components/DataProductCardItem.js, packages/data-product-mfe/src/components/ProviderForm/index.js, packages/data-product-mfe/src/components/redux/dataProduct.services.js
use serialize function while creating a data product
On click Confirm button, close delete modal
=> check for dirtyFields attribute to re-ensure form fields are dirty

packages/data-product-mfe/src/components/ConsumerForm/index.js, packages/data-product-mfe/src/components/DataProductRoutes.js
=> add condition to access array method

packages/data-product-mfe/src/components/data/Layout/CardView/DataCardItem.js, packages/data-product-mfe/src/components/data/Layout/CardView/DataCardItem.styles.scss, packages/data-product-mfe/src/components/data/data.json, packages/data-product-mfe/src/components/data/summary/index.js, packages/data-product-mfe/src/components/data/summary/styles.scss
=> include action buttons on summary page

packages/storage-mfe/src/components/Bucket/CreateBucket.js
=> update to check and disable dropdown fields if user is not an Owner in Edit page only

packages/frontend/src/components/mbc/allSolutions/AllSolutions.tsx
=> comment method componentWillReceiveProps to avoid infinite rerendering of AllSolutions

packages/data-product-mfe/src/components/dataProduct/CreateDataProduct/index.js, packages/data-product-mfe/src/components/dataTransfer/ProviderForm/ContactInformation/index.js
=> In Edit page, set default user name in Your Name field when contactinformation tab is not filled yet

packages/data-product-mfe/src/components/dataProduct/Layout/CardView/DataProductCardItem.js, packages/data-product-mfe/src/components/dataProduct/Layout/CardView/DataProductCardItem.styles.scss, packages/data-product-mfe/src/components/dataProduct/Layout/ListView/DataProductListItem.js, packages/data-product-mfe/src/components/dataProduct/Layout/ListView/DataProductListItem.styles.scss, packages/storage-mfe/src/components/Bucket/BucketList.js, packages/storage-mfe/src/components/Explorer/CustomFileActions.js, packages/storage-mfe/src/components/Explorer/FileExplorer.js, packages/storage-mfe/src/components/Explorer/redux/fileExplorer.actions.js
1. add coming soon tag on top of the card if the data product is in draft state
2. in storage, enable "copy file path" option
=> Enhancements in Data Product and Storage

packages/backend/dnambc-lib/src/main/java/com/daimler/data/assembler/UserNotificationPrefAssembler.java, packages/backend/dnambc-lib/src/main/java/com/daimler/data/db/jsonb/UserNotificationPreference.java, packages/backend/dnambc-lib/src/main/java/com/daimler/data/service/usernotificationpref/BaseUserNotificationPrefService.java, packages/backend/dnambc-lib/src/main/resources/api/UserNotificationPreference.yaml, packages/naas/naas-lib/src/main/java/com/daimler/data/dto/usernotificationpref/UserNotificationPrefVO.java, packages/naas/naas-lib/src/main/java/com/daimler/dna/notifications/common/event/config/CacheUpdateEventListener.java
=> Notification service and DnA backend service changes for chronos notifications

packages/data-product-mfe/src/components/dataTransfer/ConsumerForm/PersonalRelatedData/index.js, packages/data-product-mfe/src/components/dataTransfer/redux/dataTransfer.services.js
=> fix issue related to updating the personal related data option in consumer form with respect to that of provider form

packages/chronos/chronos-lib/src/main/java/com/daimler/data/application/client/StorageServicesClient.java, packages/chronos/chronos-lib/src/main/java/com/daimler/data/controller/ForecastController.java, packages/chronos/chronos-lib/src/main/java/com/daimler/data/service/forecast/BaseForecastService.java, packages/chronos/chronos-lib/src/main/java/com/daimler/data/service/forecast/ForecastService.java, packages/chronos/chronos-lib/src/main/resources/api/forecast.yaml
Added chronos changes on project specific config files
=> chronos changes on project specific config files

packages/storage-backend/storage-lib/src/main/java/com/daimler/data/service/storage/BaseStorageService.java
added the permission bug fixes for the buckets
=> added the permission bug fixes for the buckets

packages/dataiku/azure/ansible/roles/dataiku/tasks/main.yml
=> created ad_sync tag which will be helpful in deploying and updating the adsync

deployment/docker-compose-local-basic.yml
Fixes https://github.com/mercedes-benz/DnA/issues/1836
=> Fix 1836: Provide an image tag for vault

packages/dataiku-backend/dataiku-backend-lib/src/main/java/com/mb/dna/data/userprivilege/service/UserPrivilegeServiceImpl.java, packages/dataiku-backend/dataiku-backend-lib/src/main/resources/application.yml
Dataiku Profile name change from VISUAL-DESIGNER to VISUAL_DESIGNER
=> Dataiku profile name change

deployment/dockerfiles/matomo/matomo-be.Dockerfile, deployment/dockerfiles/matomo/matomo-mfe.Dockerfile, deployment/kubernetes/helm/charts/matomo-be/.helmignore, deployment/kubernetes/helm/charts/matomo-be/Chart.yaml, deployment/kubernetes/helm/charts/matomo-be/templates/NOTES.txt, deployment/kubernetes/helm/charts/matomo-be/templates/_helpers.tpl, deployment/kubernetes/helm/charts/matomo-be/templates/deployment.yaml, deployment/kubernetes/helm/charts/matomo-be/templates/hpa.yaml, deployment/kubernetes/helm/charts/matomo-be/templates/ingress.yaml, deployment/kubernetes/helm/charts/matomo-be/templates/networkpolicy.yaml, deployment/kubernetes/helm/charts/matomo-be/templates/pdb.yaml, deployment/kubernetes/helm/charts/matomo-be/templates/secret.yaml, deployment/kubernetes/helm/charts/matomo-be/templates/service.yaml, deployment/kubernetes/helm/charts/matomo-be/templates/serviceaccount.yaml, deployment/kubernetes/helm/charts/matomo-be/values.yaml
created matomo-be & matomo-mfe Dockerfiles and also i created a helm …
=> Matomo-be helm chart 

packages/frontend/src/components/mbc/codeSpace/newCodeSpace/NewCodeSpace.tsx, packages/frontend/src/services/utils.ts
=> Code Space changes for Creating code space form public Github repo

deployment/docker-compose-local-basic.yml, packages/storage-mfe/package.json
Fixing build issue due to tooltip-data attribute and vault image update
=> Bug on tooltip and vault image

packages/code-server/code-server-lib/src/main/java/com/daimler/data/application/client/WorkspaceJobStatusUpdateController.java
…gins whenever workspace is created
=> Commenting calling the KONG API's for creating service, route and plugins whenever workspace is created

packages/chronos-mfe/src/components/runForecastTab/RunForecastTab.js, packages/chronos-mfe/src/components/runForecastTab/runParametersForm/RunParametersForm.js, packages/chronos-mfe/src/components/tutorial/Tutorial.js
- Take out some frequency options that have not been well-tested
- Change some info texts based upon user complaints / comments
=> Minor UI changes to Chronos

packages/storage-backend/storage-lib/src/main/java/com/daimler/data/dataiku/client/DataikuClient.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/dataiku/client/DataikuClientImp.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/service/storage/BaseStorageService.java, packages/storage-backend/storage-lib/src/main/resources/application.yml, packages/storage-mfe/src/apis/buckets.api.js, packages/storage-mfe/src/components/ConnectionInfo/ConnectionModal.js, packages/storage-mfe/src/components/Utility/envs.js, packages/storage-mfe/src/server/api.js
* Dataiku connection fix
* Dataiku backend connection
=> Bugfix -connection datatiu storage (Frontend and Backend) (#2088)

README.md
This reverts commit 251526c544150c05fc5c8d9d521d5c12ab05b77c.
=> Revert "test (#2185)"

.github/secret_scanning.yml
* Create secret_scanning.yml
* Update secret_scanning.yml
=> Create secret_scanning.yml (#2179)

packages/frontend/src/components/mbc/codeSpace/newCodeSpace/NewCodeSpace.tsx, packages/frontend/src/globals/constants.ts
since we are not creating git repo for this recipe
=> Removed colloborater and gittoken for default plain recipe 

packages/data-product-mfe/src/components/dataProduct/CreateDataProduct/Description/index.js, packages/data-product-mfe/src/components/dataTransfer/ProviderForm/index.js
…int of contactinformation to logged in user name
=> Fixed DataProduct and DataTransfer Bugs

packages/trino-backend/trino-backend-lib/src/main/java/com/daimler/data/application/client/StorageServicesClient.java, packages/trino-backend/trino-backend-lib/src/main/java/com/mb/dna/datalakehouse/controller/TrinoDatalakeController.java, packages/trino-backend/trino-backend-lib/src/main/java/com/mb/dna/datalakehouse/db/jsonb/TrinoDataLakeProject.java, packages/trino-backend/trino-backend-lib/src/main/java/com/mb/dna/datalakehouse/dto/TrinoDataLakeProjectUpdateRequestVO.java, packages/trino-backend/trino-backend-lib/src/main/java/com/mb/dna/datalakehouse/dto/TrinoDataLakeProjectVO.java, packages/trino-backend/trino-backend-lib/src/main/java/com/mb/dna/datalakehouse/service/BaseTrinoDataLakeService.java, packages/trino-backend/trino-backend-lib/src/main/resources/application.yml
--1. Request validations - project name, null checks
--2. Add location for create schema stmt, 
remove location from create table stmt - didnt do, affects upload to trino functionality, reusing code
--3. Tech user - check that tech user has permission to whole schema
--4. Write permissions getting repeated (both read and write are getting repeated)
--5. Read permission - when no Collab is present, users is not mentioned in table access rule and hence exposed for everyone
--6. Add description for project , update
--7. Correct error message
--a. Failed to create bucket instead of conflict
--b. Failed to add Collab bc Storage as down
--c. All upstream fail scenarios
--d. added more log stmts
=> Added log stmts, corrected error messages, fixed access rule bugs

packages/frontend/src/components/mbc/codeSpace/codeSpaceRecipe/viewRecipe.tsx, packages/frontend/src/components/mbc/codeSpace/manageCodeSpace/CodeSpaceList.tsx
=> recipe-deploy-fix

packages/frontend/src/components/mbc/codeSpace/newCodeSpace/NewCodeSpace.tsx
disable the permission of an admin to remove himself as a collaborator and to remove his own admin permissions
=> multi admin fix

packages/frontend/src/components/mbc/codeSpace/manageCodeSpace/CodeSpaceList.tsx, packages/frontend/src/components/mbc/codeSpace/newCodeSpace/NewCodeSpace.tsx, packages/frontend/src/services/CodeSpaceApiClient.ts
=> recipe codespace list dropdown change

packages/frontend/src/components/mbc/codeSpace/codeSpaceCardItem/CodeSpaceCardItem.tsx
=> show owner info on tile

packages/frontend/src/components/mbc/codeSpace/codeSpaceRecipe/CodeSpaceRecipe.tsx, packages/frontend/src/components/mbc/codeSpace/codeSpaceRecipe/viewRecipe.tsx, packages/frontend/src/components/mbc/codeSpace/manageCodeSpace/CodeSpaceList.tsx
=> recipe bug fixes

packages/chronos/chronos-lib/src/main/java/com/daimler/data/application/config/VaultConfig.java, packages/chronos/chronos-lib/src/main/resources/application.yml, packages/code-server/code-server-lib/src/main/java/com/daimler/data/auth/client/AuthenticatorClientImpl.java, packages/code-server/code-server-lib/src/main/resources/application.yml, packages/code-server/code-server-lib/src/main/resources/db/migration/V10__insert_data.sql, packages/code-space-mfe/src/apis/codespace.api.js, packages/dataentry-mfe/src/apis/dataentry.api.js, packages/dataentry-mfe/src/components/dataEntryProjectForm/DataEntryProjectForm.js, packages/dataentry-mfe/src/pages/dataEntryProject/DataEntryProject.js, packages/dataentry-mfe/src/pages/dataEntryProjects/DataEntryProjects.js, packages/malware-scanner/malwarescan-lib/src/main/java/com/daimler/mbc/dna/malwarescanner/app/config/VaultConfig.java, packages/malware-scanner/malwarescan-lib/src/main/resources/application.yml, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/application/config/VaultConfig.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/dto/MinioObjectMetadata.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/dto/MinioObjectMetadataCollection.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/minio/client/DnaMinioClient.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/minio/client/DnaMinioClientImp.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/service/storage/BaseStorageService.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/service/storage/FixCreateDateStartUpService.java, packages/storage-backend/storage-lib/src/main/resources/application.yml, packages/trino-backend/trino-backend-lib/src/main/java/com/mb/dna/datalakehouse/controller/TrinoConnectorsDetailsController.java, packages/trino-backend/trino-backend-lib/src/main/java/com/mb/dna/datalakehouse/dto/TrinoConnectorsCollectionVO.java, packages/trino-backend/trino-backend-lib/src/main/resources/db/migration/V4__insert_data.sql
=> Release: feature/test-pr

packages/code-server/.gitignore, packages/code-server/code-server-lib/src/main/resources/application.yml
=> Release: feature/syncdev

deployment/kubernetes/helm/charts/airflow/templates/backend/deployment.yaml
=> Release: bugfix/venkat

packages/code-server/code-server-lib/src/main/java/com/daimler/data/assembler/AdditionalServiceAssembler.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/RecipeController.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/entities/CodeServerAdditionalServiceNsql.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/json/CodeServerAdditionalService.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/json/CodeServerRecipe.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/json/CodeServerRecipeDetails.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/repo/workspace/WorkspaceAdditionalServiceRepo.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/repo/workspace/WorkspaceCustomAdditionalServiceRepo.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/repo/workspace/WorkspaceCustomAdditionalServiceRepoImpl.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/dto/AdditionalPropertiesDto.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/dto/EnvironmentVariable.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/dto/Port.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/dto/SecurityContext.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/dto/VolumeMount.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseRecipeService.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/RecipeService.java, packages/code-server/code-server-lib/src/main/resources/api/WorkspaceRecipe.yaml
back-end-additional service changes recipe
=> recipe-additional-service-changes-back-end

packages/datalake-mfe/package.json, packages/datalake-mfe/src/components/dataProductForm/DataProductForm.js
=> Release: hotfix/datalakeMfe

packages/code-server/code-server-lib/src/main/java/com/daimler/data/application/client/CodeServerClient.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/application/client/GitClient.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/assembler/AdditionalServiceAssembler.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/WorkspaceController.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/repo/workspace/WorkspaceCustomAdditionalServiceRepo.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/db/repo/workspace/WorkspaceCustomAdditionalServiceRepoImpl.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/dto/AdditionalPropertiesDto.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/dto/WorkbenchManageInputDto.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseRecipeService.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java, packages/code-server/code-server-lib/src/main/resources/api/Workspace.yaml, packages/code-server/code-server-lib/src/main/resources/api/WorkspaceRecipe.yaml
=> extra-container-fix-changes

packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/WorkspaceController.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseRecipeService.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java, packages/code-server/code-server-lib/src/main/resources/api/WorkspaceRecipe.yaml
=> recipe-workpace-change-fix

packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java
=> recipe-codespace-change

packages/data-product-backend/data-product-lib/src/main/java/com/daimler/data/controller/DataProductController.java, packages/data-product-backend/data-product-lib/src/main/resources/application.yml, packages/data-product-backend/data-product-lib/src/main/resources/graphql/dataproducts.graphqls, packages/data-product-mfe/package.json, packages/data-product-mfe/src/Utility/formData.js, packages/data-product-mfe/src/components/dataProduct/dataProductList.js, packages/data-product-mfe/src/components/dataTransfer/ConsumerForm/ContactInformation/index.js, packages/data-product-mfe/src/components/dataTransfer/ConsumerForm/index.js, packages/data-product-mfe/src/components/dataTransfer/Layout/CardView/DataTransferCardItem.js, packages/data-product-mfe/src/components/dataTransfer/ProviderForm/ContactInformation/index.js
Release: feature/dataproductchanges
=> Release: feature/dataproductchanges

packages/code-server/code-server-lib/src/main/java/com/daimler/data/application/client/CodeServerClient.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java
cs-recipe-change-instruction-set-fix
=> cs-recipe-change-instructionset-fix

packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseRecipeService.java
=> cs-recipe-extensions

packages/data-product-mfe/package.json, packages/data-product-mfe/src/Utility/formData.js, packages/data-product-mfe/src/components/dataTransfer/ConsumerForm/ContactInformation/index.js, packages/data-product-mfe/src/components/dataTransfer/ConsumerForm/index.js, packages/data-product-mfe/src/components/dataTransfer/ProviderForm/ContactInformation/index.js
=> Release: feature/leanIXNew

packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/RecipeController.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/WorkspaceController.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseRecipeService.java
=> cs-recipe-bug-fixes

packages/code-server/code-server-lib/src/main/resources/application.yml
cs-recipe-post-construct-change
=> cs-recipe-post-construct-change

packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/RecipeDetailsUpdate.java
=> cs-recipe-migration

packages/code-server/code-server-lib/src/main/java/com/daimler/data/application/client/GitClient.java
=> recipe-outside-org-fix

packages/code-space-mfe/src/components/CodeSpace.js, packages/code-space-mfe/src/components/codeSpaceCardItem/CodeSpaceCardItem.js, packages/code-space-mfe/src/components/newCodeSpace/NewCodeSpace.js
update the max cpu and ram on the tile based on the resource field under recipe details in workspaces api.
=> show cpu and ram based on the resource field

packages/code-space-mfe/src/components/deployModal/DeployModal.js
remove vault injector enabled field during deployment
=> remove vault injector enabled field from UI

packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java
=> cs-recipe-fix

packages/chronos-mfe/src/components/runForecastTab/inputFileArea/InputFileArea.js
*text changes requested by the chronos team
=> wording change

packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/WorkspaceController.java
=> isdeployEnabled-fix

packages/chronos/chronos-lib/src/main/java/com/daimler/data/application/client/StorageServicesClient.java, packages/chronos/chronos-lib/src/main/resources/application.yml
Release: bugfix/chronos-config-issue-fix
=> Release: bugfix/chronos-config-issue-fix

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/codeSpaceTutorials/CodeSpaceTutorials.js
Release: feature/CodeSpaceVideo
=> Release: feature/CodeSpaceVideo

packages/code-space-mfe/package.json, packages/code-space-mfe/src/Utility/constants.js, packages/code-space-mfe/src/components/CodeSpace.js, packages/frontend/package.json, packages/frontend/src/components/mbc/filters/FilterWrapper.scss, packages/frontend/src/components/mbc/filters/FilterWrapper.tsx, packages/frontend/src/components/mbc/filters/SolutionsFilter.tsx
Release: bugfix/EmailUseCaseOwnerAlignment
=> Release: bugfix/EmailUseCaseOwnerAlignment

packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/WorkspaceController.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java
=> resource-changes-fix

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/CodeSpace.js, packages/code-space-mfe/src/components/codeSpaceCardItem/CodeSpaceCardItem.js
Release: bugfix/ContextMenuAlignment
=> Release: bugfix/ContextMenuAlignment

packages/code-server/code-server-lib/src/main/resources/application.yml
Release: feature/code-server-version
=> Release: feature/code-server-version

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/CodeSpace.js, packages/code-space-mfe/src/components/codeSpaceCardItem/CodeSpaceCardItem.js, packages/code-space-mfe/src/components/deployModal/DeployModal.js, packages/code-space-mfe/src/components/vaultManagement/VaultManagement.js, packages/frontend/package.json, packages/frontend/src/components/formElements/tags/Tags.tsx
Release: feature/branchSeach-env-CS
=> Release: feature/branchSeach-env-CS

packages/fabric-backend/lib/src/main/java/com/daimler/data/application/client/FabricWorkspaceClient.java, packages/fabric-backend/lib/src/main/resources/application.yml
Release: hotfix/fabricException
=> Release: hotfix/fabricException

packages/frontend/package.json, packages/frontend/src/components/mbc/admin/taghandling/TagHandling.tsx
Release: hotfix/SolutionMBM-division
=> Release: hotfix/SolutionMBM-division

packages/dataiku-backend/dataiku-backend-lib/src/main/resources/application.yml, packages/dss-mfe/package.json, packages/dss-mfe/src/components/CreateOrEditProject/CreateOrEditProject.scss, packages/dss-mfe/src/components/CreateOrEditProject/index.js
=> Release: feature/dataikuTou

packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/RepoSoftwareFileUpdate.java
=> software-migration

packages/code-server/code-server-lib/src/main/resources/application.yml
=> software-migration-version-change

packages/code-server/code-server-lib/src/main/resources/application.yml
=> vault file name

packages/code-server/code-server-lib/src/main/java/com/daimler/data/auth/client/AuthenticatorClientImpl.java, packages/code-server/code-server-lib/src/main/resources/application.yml
=> Release: hotfix/kong

packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/WorkspaceController.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/WorkspaceService.java, packages/code-server/code-server-lib/src/main/resources/api/Workspace.yaml, packages/code-server/code-server-lib/src/main/resources/application.yml
=> bootcamp-api-for-collab

packages/frontend/package.json, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/service/storage/BaseStorageService.java, packages/storage-backend/storage-lib/src/main/resources/application.yml, packages/storage-mfe/package.json
Release: hotfix/storageNullcheck
=> Release: hotfix/storageNullcheck

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/codeSpaceTutorials/CodeSpaceTutorials.js, packages/code-space-mfe/src/components/codeSpaceTutorials/CodeSpaceTutorials.scss
Release: feature/videoTutorails
=> Release: feature/videoTutorails

packages/fabric-backend/lib/src/main/java/com/daimler/data/application/client/FabricWorkspaceClient.java, packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/BaseFabricWorkspaceService.java, packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/WorkspaceBackgroundJobsService.java, packages/fabric-backend/lib/src/main/resources/application-dev.yml, packages/fabric-backend/lib/src/main/resources/application.yml
Release: feature/HandleRateLimiterInFabric
=> Release: feature/HandleRateLimiterInFabric

packages/fabric-backend/lib/src/main/java/com/daimler/data/application/client/AuthoriserClient.java, packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/BaseFabricWorkspaceService.java, packages/fabric-backend/lib/src/main/resources/application-dev.yml, packages/fabric-backend/lib/src/main/resources/application.yml
Release: feature/useExistingEntitlementsRolesIfConflict
=> Release: feature/useExistingEntitlementsRolesIfConflict

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/CodeSpace.js
Release: feature/hotfix-cloudservice
=> Release: feature/hotfix-cloudservice

packages/code-server/code-server-lib/src/main/java/com/daimler/data/application/client/CodeServerClient.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java, packages/code-server/code-server-lib/src/main/resources/application.yml, packages/code-space-mfe/package.json, packages/code-space-mfe/src/common/globals/css/main.scss, packages/code-space-mfe/src/components/AllCodeSpaces.js, packages/code-space-mfe/src/components/codeSpaceCardItem/CodeSpaceCardItem.js, packages/code-space-mfe/src/components/newCodeSpace/NewCodeSpace.js, packages/frontend/package.json, packages/frontend/src/globals/css/main.scss
Release: hotfix/cs-collab-uiImprovements
=> Release: hotfix/cs-collab-uiImprovements

packages/fabric-backend/lib/src/main/java/com/daimler/data/application/main/Application.java, packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/BaseFabricWorkspaceService.java, packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/WorkspaceBackgroundJobsService.java, packages/fabric-backend/lib/src/main/resources/application-dev.yml, packages/fabric-backend/lib/src/main/resources/application.yml
Release: bugfix/onboardexistingOwnersToFabricEnabled
=> Release: bugfix/onboardexistingOwnersToFabricEnabled

packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java, packages/code-server/code-server-lib/src/main/resources/application.yml
Release: hotfix/addingCloudServiceProvider
=> Release: hotfix/addingCloudServiceProvider

packages/code-server/code-server-lib/src/main/java/com/daimler/data/auth/client/WorkspaceMigration.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/WorkspaceController.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java, packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/WorkspaceService.java, packages/code-server/code-server-lib/src/main/resources/application.yml
=> aws-migration

packages/storage-backend/storage-lib/src/main/java/com/daimler/data/minio/client/DnaMinioClientImp.java, packages/storage-backend/storage-lib/src/main/resources/application.yml
Release: hotfix/storage-list-users
=> Release: hotfix/storage-list-users

packages/code-server/code-server-lib/src/main/java/com/daimler/data/service/workspace/BaseWorkspaceService.java, packages/code-server/code-server-lib/src/main/resources/application.yml
Release: hotfix/transferOwnerFix
=> Release: hotfix/transferOwnerFix

packages/code-space-mfe/src/components/AllCodeSpaces.js, packages/code-space-mfe/src/components/AllCodeSpaces.scss
Release: feature/cs-aws-faq-update
=> Release: feature/cs-aws-faq-update

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/AllCodeSpaces.js, packages/code-space-mfe/src/components/AllCodeSpaces.scss
Release: feature/cs-aws-improvements
=> Release: feature/cs-aws-improvements

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/AllCodeSpaces.js, packages/code-space-mfe/src/components/AllCodeSpaces.scss
Release: feature/cs-aws-warning-msg-update
=> Release: feature/cs-aws-warning-msg-update

packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/BaseFabricWorkspaceService.java, packages/fabric-backend/lib/src/main/resources/application.yml
Release: hotfix/roles-startsWith
=> Release: hotfix/roles-startsWith

packages/naas/naas-lib/src/main/java/com/daimler/dna/notifications/common/event/config/RedisCacheUtil.java, packages/naas/naas-lib/src/main/resources/application.yml
=> Release: hotfix/naas-update

packages/naas/naas-lib/src/main/java/com/daimler/dna/notifications/common/event/config/CacheUpdateEventListener.java, packages/naas/naas-lib/src/main/java/com/daimler/dna/notifications/core/service/KafkaCoreCampaignService.java, packages/naas/naas-lib/src/main/resources/application.yml
=> Release: feature/naaschanges

packages/dataiku-backend/dataiku-backend-lib/src/main/java/com/mb/dna/data/dataiku/api/controller/DataikuController.java, packages/dataiku-backend/dataiku-backend-lib/src/main/resources/application.yml
Release: feature/dataikuChanges
=> Release: feature/dataikuChanges

packages/naas/naas-lib/src/main/java/com/daimler/dna/notifications/controller/NotificationsController.java
Release: feature/setting-email
=> Release: feature/setting-email

packages/fabric-backend/lib/src/main/resources/api/fabricWorkspaces.yaml, packages/fabric-backend/lib/src/main/resources/application.yml, packages/frontend/package.json, packages/frontend/src/components/mbc/aliceRoleRequest/AliceRoleRequest.tsx
Release: bugfix/Alice-Role-CaseSensitivity
=> Release: bugfix/Alice-Role-CaseSensitivity

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/codeSpaceTutorials/CodeSpaceTutorials.js
Release: bugfix/video-tutorial
=> Release: bugfix/video-tutorial

packages/chronos-mfe/config/webpack.config.js, packages/chronos-mfe/config/webpack.prod.config.js, packages/code-space-mfe/config/webpack.config.js, packages/code-space-mfe/config/webpack.prod.config.js, packages/data-product-mfe/config/webpack.config.js, packages/data-product-mfe/config/webpack.prod.config.js, packages/datalake-mfe/config/webpack.config.js, packages/datalake-mfe/config/webpack.prod.config.js, packages/dss-mfe/config/webpack.config.js, packages/dss-mfe/config/webpack.prod.config.js, packages/fabric-mfe/config/webpack.config.js, packages/fabric-mfe/config/webpack.prod.config.js, packages/matomo-mfe/config/webpack.config.js, packages/matomo-mfe/config/webpack.prod.config.js, packages/power-platform-mfe/config/webpack.config.js, packages/power-platform-mfe/config/webpack.prod.config.js, packages/storage-mfe/webpack.config.js, packages/storage-mfe/webpack.prod.config.js
=> Release: hotfix/buildfix

packages/storage-backend/storage-lib/src/main/java/com/daimler/data/minio/client/DnaMinioClient.java, packages/storage-backend/storage-lib/src/main/java/com/daimler/data/minio/client/DnaMinioClientImp.java, packages/storage-backend/storage-lib/src/main/resources/application.yml
=> Release: bugfix/mc-delete

packages/frontend/package.json, packages/frontend/src/components/DatePicker/DatePicker.scss, packages/frontend/src/components/DatePicker/DatePicker.tsx
Release: hotfix/date-picker-fix
=> Release: hotfix/date-picker-fix

packages/code-server/code-server-lib/src/main/java/com/daimler/data/auth/client/AuthenticatorClientImpl.java, packages/code-server/code-server-lib/src/main/resources/application.yml
=> Release: bugfix/cs-apiKey-fix

packages/storage-backend/storage-lib/src/main/java/com/daimler/data/minio/client/DnaMinioClientImp.java, packages/storage-backend/storage-lib/src/main/resources/application.yml
Release: bugfix/minio-policy-change
=> Release: bugfix/minio-policy-change

packages/code-server/code-server-lib/src/main/java/com/daimler/data/controller/WorkspaceController.java, packages/code-server/code-server-lib/src/main/resources/application.yml
Release: hotfix/securityConfigFix
=> Release: hotfix/securityConfigFix

packages/storage-mfe/package.json, packages/storage-mfe/src/components/Bucket/CreateBucket.js
Release: bugfix/storage-bucket-validation
=> Release: bugfix/storage-bucket-validation

packages/storage-backend/storage-lib/src/main/java/com/daimler/data/minio/client/DnaMinioClientImp.java, packages/storage-backend/storage-lib/src/main/resources/application.yml
=> Release: bugfix/removeAlias

packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/BaseFabricWorkspaceService.java, packages/fabric-backend/lib/src/main/resources/application.yml
=> Release: hotfix/loggers

packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/AllCodeSpaces.js, packages/code-space-mfe/src/components/AllCodeSpaces.scss
Release: hotfix/cs-aws-warning-update
=> Release: hotfix/cs-aws-warning-update

packages/storage-backend/storage-lib/src/main/java/com/daimler/data/minio/client/DnaMinioClientImp.java, packages/storage-backend/storage-lib/src/main/resources/application.yml
=> Release: hotfix/dataLogger

packages/chronos-mfe/package.json, packages/chronos-mfe/src/components/chronosProjectForm/ChronosProjectForm.js, packages/code-space-mfe/package.json, packages/code-space-mfe/src/components/newCodeSpace/NewCodeSpace.js, packages/dataentry-mfe/package.json, packages/dataentry-mfe/src/components/dataEntryProjectForm/DataEntryProjectForm.js, packages/fabric-mfe/package.json, packages/fabric-mfe/src/components/fabricWorkspaceForm/FabricWorkspaceForm.js, packages/frontend/package.json, packages/frontend/src/components/mbc/createNewReport/description/Description.tsx, packages/storage-mfe/package.json, packages/storage-mfe/src/components/Bucket/CreateBucket.js
Release: feature/archerID-validation
=> Release: feature/archerID-validation

packages/fabric-backend/lib/build.gradle, packages/fabric-backend/lib/src/main/java/com/daimler/data/application/config/SchedulerConfig.java, packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/BaseFabricWorkspaceService.java, packages/fabric-backend/lib/src/main/java/com/daimler/data/service/fabric/WorkspaceBackgroundJobsService.java, packages/fabric-backend/lib/src/main/resources/application.yml, packages/fabric-backend/lib/src/main/resources/db/migration/V3__create_table.sql, packages/fabric-mfe/package.json, packages/fabric-mfe/src/components/fabricWorkspaceCard/FabricWorkspaceCard.js, packages/fabric-mfe/src/utilities/utils.js
Release: feature/implemetSchedLock
=> Release: feature/implemetSchedLock

packages/frontend/package.json, packages/frontend/src/globals/landingPageElements.ts
Release: hotfix/toolsLandingPage
=> Release: hotfix/toolsLandingPage
